apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: p-exporter-app
  name: p-exporter-app
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: p-exporter-app
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: p-exporter-app
    spec:
      containers:
      - image: local.registry/camunda-app:1.0.0
        imagePullPolicy: IfNotPresent
        name: camunda-app
      - image: local.registry/p-exporter-app:1.0.0
        name: p-exporter-app
        env:
          - name: APP_PORT
            value: "2113"
          - name: APP_DEBUG
            value: "true"
          - name: DOCKERHUB_ORGANIZATION
            value: amazon
          - name: IMAGE_TIME_FRAME_SECONDS
            value: "13114080"
          - name: DOCKERHUB_REGISTRY_URL
            value: "https://hub.docker.com/v2/repositories"
---
apiVersion: v1
kind: Service
metadata:
  name: p-exporter-app
  namespace: default
spec:
  selector:
    app: p-exporter-app
  ports:
    - protocol: TCP
      port: 2113
      targetPort: 2113
  type: NodePort