apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "app.fullname" . }}
spec:
  replicas: {{ .Values.replicaCount }} 
  selector:
    matchLabels:
      app: {{ include "app.fullname" . }} 
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/app-configmap.yaml") . | sha256sum }}
      labels:
        app: {{ include "app.fullname" . }}
    spec:
      containers:
      - image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        imagePullPolicy: IfNotPresent
        name: {{ include "app.fullname" . }}
        envFrom:
          - configMapRef:
              name: {{ include "app.fullname" . }}-config